import sys
import re
from pathlib import Path
from ruamel.yaml import YAML
from aksharamukha import transliterate
from bs4 import BeautifulSoup
import requests

# Add project root to path
sys.path.append(str(Path(__file__).parent.parent))
from src.adapters import AnkiConnectAdapter

DEVANAGARI_CHARS = [
    # Vowels
    'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ए', 'ऐ', 'ओ', 'औ', 'अं', 'अः',
    # Consonants
    'क', 'ख', 'ग', 'घ', 'ङ',
    'च', 'छ', 'ज', 'झ', 'ञ',
    'ट', 'ठ', 'ड', 'ढ', 'ण',
    'त', 'थ', 'द', 'ध', 'न',
    'प', 'फ', 'ब', 'भ', 'म',
    'य', 'र', 'ल', 'व',
    'श', 'ष', 'स', 'ह',
    'ळ', 'क्ष', 'ज्ञ'
]

# --- Static Content for Local Files ---

CSS = """
.card {
    font-family: sans-serif;
    text-align: center;
    background-color: #fdf6e3;
    color: #333;
}
.char-big {
    font-size: 120px;
    color: #b58900;
    margin: 20px;
}
.char-small {
    font-size: 40px;
    color: #b58900;
    margin-right: 10px;
}
.name {
    font-size: 30px;
    font-weight: bold;
    color: #268bd2;
}
.ipa {
    font-family: "Charis SIL", serif;
    color: #657b83;
    font-style: italic;
}
.meta {
    color: #93a1a1;
    margin: 10px 0;
    font-size: 0.9em;
}
.stroke-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
    gap: 20px;
    margin: 20px;
}
.stroke-box img {
    height: 150px;
    border: 1px solid #ddd;
    background: #fff;
    padding: 5px;
    border-radius: 5px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}
.examples {
    text-align: left;
    margin: 20px;
    background: #fff;
    padding: 15px;
    border-radius: 8px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.05);
}
.prompt {
    color: #aaa;
    margin-top: 50px;
    text-transform: uppercase;
    font-size: 0.8em;
}
"""

FRONT_TEMPLATE = """
<div class="card-content">
    <div class="char-big">{{Character}}</div>
    <div class="static-img">{{Image_Static}}</div>
    <div class="prompt">What is this character?</div>
</div>
"""

BACK_TEMPLATE = """
<div class="card-content">
    <div class="header">
        <span class="char-small">{{Character}}</span>
        <span class="name">{{Name}}</span>
        <span class="ipa">/{{IPA}}/</span>
    </div>
    <hr>
    <div class="meta">{{Category}} <br> {{Description}}</div>
    
    <div class="stroke-container">
        <div class="stroke-box">{{Image_Stroke_1}}</div>
        <div class="stroke-box">{{Image_Stroke_2}}</div>
    </div>
    
    <div class="examples">{{Examples}}</div>
</div>
"""

def fetch_wiktionary_data(char):
    """Scrape IPA/Desc with fallback."""
    url = f"https://en.wiktionary.org/wiki/{char}"
    data = {"IPA": "", "Description": ""}
    try:
        res = requests.get(url)
        if res.status_code == 200:
            soup = BeautifulSoup(res.content, "html.parser")
            ipa_span = soup.find("span", class_="IPA")
            if ipa_span:
                data["IPA"] = ipa_span.get_text(strip=True)
            
            content_div = soup.find("div", class_="mw-parser-output")
            if content_div:
                for p in content_div.find_all("p"):
                    text = p.get_text()
                    if "consonant" in text or "vowel" in text or "letter" in text:
                        text = re.sub(r'\[\d+\]', '', text)
                        data["Description"] = text.strip()
                        break
    except: pass

    if not data["IPA"]:
        try:
            data["IPA"] = transliterate.process('Devanagari', 'IPA', char)
        except: pass
        
    return data

def build():
    adapter = AnkiConnectAdapter()
    deck_name = "Devanagari Alphabet"
    model_name = "Devanagari_Master"
    
    # 1. Setup Model (Fields Only)
    try:
        adapter.create_deck(deck_name)
    except: pass
    
    fields = ["Character", "Name", "IPA", "Category", "Description", 
              "Image_Stroke_1", "Image_Stroke_2", "Image_Static", "Examples", "Example_Audio_Source"]
    
    try:
        adapter.create_model(model_name, fields, css="")
        print(f"✅ Model {model_name} checked.")
    except: pass

    # 2. Generate Local Files (Config, CSS, Templates)
    output_dir = Path("devanagari_project/data")
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Config
    config_data = {
        "anki_model_name": model_name,
        "description": "Devanagari Alphabet Deck generated by Anki Vibe",
        "templates": {
            "Card 1": "card_1"
        }
    }
    with open(output_dir / "config.yaml", "w", encoding="utf-8") as f:
        yaml = YAML()
        yaml.dump(config_data, f)
        
    # CSS
    with open(output_dir / "style.css", "w", encoding="utf-8") as f:
        f.write(CSS.strip())
        
    # Templates
    with open(output_dir / "card_1_front.html", "w", encoding="utf-8") as f:
        f.write(FRONT_TEMPLATE.strip())
        
    with open(output_dir / "card_1_back.html", "w", encoding="utf-8") as f:
        f.write(BACK_TEMPLATE.strip())
        
    print("✅ Generated Config, CSS, and Template files.")

    # 3. Scan Media Dump & Generate Notes
    existing_map = {} 
    notes_path = output_dir / "notes.yaml"
    
    yaml = YAML()
    yaml.preserve_quotes = True
    yaml.width = 4096

    if notes_path.exists():
        try:
            with open(notes_path, "r", encoding="utf-8") as f:
                old_notes = yaml.load(f) or []
                for n in old_notes:
                    char = n["fields"].get("Character")
                    nid = n.get("id")
                    if char and nid:
                        existing_map[char] = nid
            print(f"Loaded {len(existing_map)} existing IDs.")
        except Exception as e:
            print(f"⚠️ Failed to load existing notes: {e}")

    media_dump_dir = Path("devanagari_project/media_dump")
    if not media_dump_dir.exists():
        print("❌ Media dump not found.")
        return
        
    all_files = list(media_dump_dir.glob("*"))
    print(f"Found {len(all_files)} files in dump.")
    
    notes = []
    
    print("🚀 Processing Characters...")
    for char in DEVANAGARI_CHARS:
        print(f"Processing {char}...")
        
        stroke1 = "" 
        stroke2 = "" 
        static = ""  
        
        for f in all_files:
            if char in f.name:
                try:
                    adapter.store_media_file(filename=f.name, path=str(f.absolute()))
                    
                    img_tag = f'<img src="{f.name}">'
                    
                    if f.suffix.lower() == ".gif":
                        if "Deva-" in f.name and "-order" in f.name:
                            stroke1 = img_tag
                        else:
                            stroke2 = img_tag
                    elif f.suffix.lower() == ".svg":
                        static = img_tag
                except Exception as e:
                    print(f"  ⚠️ Error uploading {f.name}: {e}")

        wiki_data = fetch_wiktionary_data(char)
        name = transliterate.process('Devanagari', 'ISO', char)
        current_id = existing_map.get(char)
        
        notes.append({
            "id": current_id,
            "deck": deck_name,
            "tags": ["devanagari_alphabet"],
            "fields": {
                "Character": char,
                "Name": name,
                "IPA": wiki_data["IPA"],
                "Category": "Vowel" if char in ['अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ए', 'ऐ', 'ओ', 'औ', 'अं', 'अः'] else "Consonant",
                "Description": wiki_data["Description"],
                "Image_Stroke_1": stroke1,
                "Image_Stroke_2": stroke2,
                "Image_Static": static,
                "Examples": "", 
                "Example_Audio_Source": ""
            }
        })

    with open(notes_path, "w", encoding="utf-8") as f:
        yaml.dump(notes, f)
        
    print(f"✅ Generated {len(notes)} notes.")

if __name__ == "__main__":
    build()